server:
  port: 8080

spring:
  application:
    name: gateway-service
  webflux:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: book-service-route
          uri: lb://book-service
          predicates:
            - Path=/api/book/**
        - id: borrow-service-route
          uri: lb://borrow-service
          predicates:
            - Path=/api/borrow/**
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
